package net.spikesync.pingerdeamonrabbitmqclient;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.test.RabbitListenerTest;
import org.springframework.amqp.rabbit.test.context.SpringRabbitTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.beans.factory.config.AutowireCapableBeanFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.ImportResource;
import org.springframework.test.context.ContextConfiguration;

import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.junit4.SpringRunner;

import net.spikesync.pingerdaemonrabbitmqclient.PropertiesLoader;
import net.spikesync.pingerdaemonrabbitmqclient.SilverCloudNode;

import org.junit.jupiter.api.condition.EnabledIf;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;

import java.util.Properties;

//@ImportResource("beans.xml")
//@SpringBootTest(classes = PingerdaemonRabbitmqClientApplication.class)
//@ComponentScan
//@RunWith(SpringJUnit4ClassRunner.class)

//@ExtendWith(SpringExtension.class)
@ContextConfiguration("classpath:beans.xml")
//@RabbitListenerTest
//@SpringJUnitConfig
//@SpringRabbitTest
class PingerdaemonRabbitmqClientApplicationTests {

 //   private static final Logger logger = LoggerFactory.getLogger(PingerdaemonRabbitmqClientApplicationTests.class);
	private static final Logger logger = LoggerFactory.getLogger(PingerdaemonRabbitmqClientApplicationTests.class);

	@Autowired
	ApplicationContext context;
	
	@Autowired
	private SilverCloudNode sc;

	@Value("${logging.level.net.spikesync}")
	private String logginglevel;
	
	@Value("${test-silvercloud-scnodes}")
	private String testingEnabled;
	
	private Properties prop;

	public PingerdaemonRabbitmqClientApplicationTests() {
 		prop = PropertiesLoader.loadProperties();
	}
	
	@Test
//	@EnabledIf("testingEnabled")
	void contextLoads() {
		logger.info("##################### Value of property test-silvercloud-scnodes: "+ testingEnabled);
		logger.debug("************** ========= Property test-silvercloud-scnodes is set to: "  + prop.getProperty("test-silvercloud-scnodes"));
		
		if(context!=null)
			logger.info("**************** AutowiredCapableBeanFactory: " + context.toString());

		else {
			logger.info("ApplicationContext variable is null!!");
			return;
		}
		assertThat(context).isNotNull();
		assertThat(context.getBean(net.spikesync.pingerdaemonrabbitmqclient.SilverCloud.class)).isNotNull();

	}
	 @SuppressWarnings("unused") // This method is used by JUnit 5 @EnabledIf, i.e., it is generated by JUnit and not used by methods of net.spikesync.devping.DevPingApplicationTest
		private boolean testingEnabled() {
		 return false;
	 }
	 

}
